# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_add_base_model_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='send_days_offset',
            field=models.IntegerField(default=0, help_text='The number of days before (negative) or after (positive) the send event to send this message.'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='send_time',
            field=models.TimeField(default=None, help_text='The clock time to send a message', null=True),
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment'),
        ),
    ]
