# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-06 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_add_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='send_hours_offset',
            field=models.IntegerField(default=0, help_text='The number of hours before (negative) or after (positive) the send event to send this message. Cannot be used when a send time is set.'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='send_event',
            field=models.CharField(choices=[('a', 'Appointment Attended'), ('u', 'Appointment Updated'), ('c', 'Appointment Created'), ('d', 'Appointment Deleted')], help_text='The event on which the sending of this message is based.', max_length=1),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='send_time',
            field=models.TimeField(default=None, help_text='The clock time to send a message. Cannot be used when a send hours offset is set.', null=True),
        ),
    ]
