# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 00:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=32)),
                ('client_last_name', models.CharField(max_length=32)),
                ('client_email', models.CharField(max_length=255, null=True)),
                ('client_phone', models.CharField(max_length=40, null=True)),
                ('client_language', models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish')], default='EN', max_length=2)),
                ('time', models.DateTimeField()),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.Appointment')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.MessageTemplate')),
            ],
        ),
    ]
