# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=32)),
                ('client_last_name', models.CharField(max_length=32)),
                ('client_email', models.CharField(max_length=255, null=True)),
                ('client_phone', models.CharField(max_length=40, null=True)),
                ('client_language', models.CharField(max_length=40)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=40)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
