# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
