# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20170305_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
