# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20170305_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
