# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    AppointmentType = apps.get_model('appointments', 'AppointmentType')
    AppointmentType.objects.create(name='Subsidized Child Care 6 Month Check-in')

def backwards(apps, schema_editor):
    AppointmentType = apps.get_model('appointments', 'AppointmentType')
    AppointmentType.objects.all().delete()


class Migration(migrations.Migration):


    dependencies = [
        ('appointments', '0003_allow_blank_client_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.AppointmentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='appointment_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='appointments.AppointmentType'),
            preserve_default=False,
        ),
    ]
