# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 23:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_add_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='send_time',
            field=models.TimeField(default=datetime.datetime(2017, 4, 15, 16, 4, 32, 186148)),
            preserve_default=False,
        ),
    ]
