# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_add_template_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_language',
            field=models.CharField(max_length=16),
        ),
    ]
