# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_counselor',
            field=models.BooleanField(default=True, verbose_name='Counselor'),
        ),
    ]
