# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveIntegerField()),
                ('send_time', models.TimeField()),
                ('title', models.CharField(max_length=40)),
                ('text', models.TextField(max_length=1000)),
                ('appointment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_templates', to='appointment.AppointmentType')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointment.Appointment')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='message.MessageTemplate')),
            ],
        ),
    ]
