# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetemplate',
            name='days_before',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='send_days_offset',
            field=models.IntegerField(help_text='The number of days before (negative) or after (positive) the send event to send this message.', null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='send_event',
            field=models.CharField(choices=[('c', 'Appointment Created'), ('u', 'Appointment Updated'), ('d', 'Appointment Deleted'), ('a', 'Appointment Attended')], default='a', help_text='The event on which the sending of this message is based.', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='send_time',
            field=models.TimeField(help_text='The clock time to send a message', null=True),
        ),
    ]
