# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(blank=True, max_length=32)),
                ('client_last_name', models.CharField(blank=True, max_length=32)),
                ('client_email', models.CharField(blank=True, max_length=255)),
                ('client_phone', models.CharField(blank=True, max_length=40)),
                ('client_language', models.CharField(max_length=16)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointment.AppointmentType'),
        ),
    ]
