# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_counselor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
